# Script for analysis of filtered SVs generated by PacBio SV caller pipeline

function_file <- '/home/grabowsky/tools/workflows/poplar_branch_indels/r_scripts/pb_SV_analysis_functions.r'
source(function_file)

library(ggplot2)
library(reshape2)
library(gridExtra)
library(ape)

# LOAD DATA #
data_dir <- '/home/t4c1/WORK/grabowsk/data/poplar_branches/SV_calling_analysis/new_PB_SVcaller/'
combo_file <- 'ref.ALLData.vcf'
combo_file_tot <- paste(data_dir, combo_file, sep = '')
combo_df <- make_combo_indel_df(combo_file_tot)

# age distances based on distance from tip-to-tip of branches using 
#   age estimages of branches, nodes, and trunks
age_dist_file <- '/home/t4c1/WORK/grabowsk/data/poplar_branches/SV_calling_analysis/age_dist_matrix.tsv'
age_dist_mat <- read.table(age_dist_file, header = T, stringsAsFactors = F, 
  sep = '\t', row.names = 1)

# similar to first age matrix but with fixed age distance between branches
#  from different trees
age_dist_file_v2 <- '/home/t4c1/WORK/grabowsk/data/poplar_branches/SV_calling_analysis/age_dist_matrix_v2.tsv'
age_dist_mat_v2 <- read.table(age_dist_file_v2, header = T, 
  stringsAsFactors = F, sep = '\t', row.names = 1)

# using age-distance between nodes rather than tips of branches
age_dist_file_v3 <- '/home/t4c1/WORK/grabowsk/data/poplar_branches/SV_calling_analysis/age_dist_matrix_v3.tsv'
age_dist_mat_v3 <- read.table(age_dist_file_v3, header = T, 
  stringsAsFactors = F, sep = '\t', row.names = 1)


meta_in <- '/home/t4c1/WORK/grabowsk/data/poplar_branches/meta/poplar_branch_meta_v4.0.txt'
samp_meta <- read.table(meta_in, header = T, stringsAsFactors = F, sep = '\t')
# samp_meta[,c('lib_name', 'branch_name')]

## Remove bad branches
bad_branches <- c('13.4', '14.1')
bad_samps <- c()
for(bb in bad_branches){
  tmp_ind <- which(as.character(samp_meta$branch_name) == bb)
  bad_samps <- c(bad_samps, samp_meta$lib_name[tmp_ind])
}

bad_vcf_cols <- c()
for(bs in bad_samps){
  tmp_col_ind <- which(colnames(combo_df) == bs)
  bad_vcf_cols <- c(bad_vcf_cols, tmp_col_ind)
}

combo_df_filt <- combo_df[ , -sort(bad_vcf_cols)]

# Change order of samples and make name vector for SV_df

branch_name_ord <- c(13.1, 13.2, 13.3, 14.5, 13.5, 14.4, 14.3, 14.2)
lib_name_ord <- c()
for(bn in branch_name_ord){
  tmp_ind <- which(samp_meta$branch_name == bn)
  lib_name_ord <- c(lib_name_ord, samp_meta$lib_name[tmp_ind])
}
branch_name_vec <- paste('branch', branch_name_ord, sep = '_')

first_samp_col <- which(colnames(combo_df_filt) == 'FORMAT') + 1
last_samp_col <- which(colnames(combo_df_filt) == 'full_name') - 1

combo_df_filt[, c(first_samp_col:last_samp_col)] <- combo_df_filt[,lib_name_ord]
colnames(combo_df_filt)[c(first_samp_col:last_samp_col)] <- lib_name_ord

# make filtered metadata

fs_inds <- c()
for(bn in branch_name_ord){
  tmp_m_ind <- which(samp_meta$branch_name == bn)
  fs_inds <- c(fs_inds, tmp_m_ind)
}

samp_meta_filt <- samp_meta[fs_inds, ]

# make basic dataframe to tally genotypes
basic_samp_tab_df <- data.frame(lib = lib_name_ord,
  branch = factor(branch_name_vec, levels = branch_name_vec),
  tree = c(rep('13', times = 4), rep('14', times = 4)),
  homRef = NA, het = NA, homAlt = NA,
  stringsAsFactors = F)

basic_singleton_df <- data.frame(lib = lib_name_ord,
  branch = factor(branch_name_vec, levels = branch_name_vec),
  tree = c(rep('13', times = 4), rep('14', times = 4)),
  homRef = 0, het = 0, homAlt = 0, stringsAsFactors = F)

##########################################################
# First Genotypes: strict, 100bp min
precall_filt_df_1 <- precalling_SV_filtering(sv_geno_df = combo_df_filt,
  mer_length = 8, per_mn_cutoff = 0.7, per_bn_pure_cutoff = 0.5, 
  per_bn_multi_cutoff = 0.6, dist_cut = 1000, sd_cut = 3, use_sd = T)

combo_genotypes_1 <- generate_filtered_genotypes(combo_df = precall_filt_df_1,
  min_sv_coverage = 10, het_ratio_cut = 0.25, min_minor_allele_count = 2,
  max_hom_ratio = 0.05, est_error = 0.032, est_penetrance = 0.35,
  good_score = 0.9, great_score = 0.98, same_geno_bonus = 0.67,
  ss_min_cov = 20)

combo_genos_noNA_32 <- filt_geno_mat(geno_mat = combo_genotypes_1,
  max_nas = 0, min_length = 32)

# generate distance matrix and trees
geno3_t <- t(combo_genos_noNA_32)

rownames(geno3_t) <- branch_name_vec
geno3_dist_mat <- dist(geno3_t, method = 'manhattan', diag = T,
  upper = T)

library(vegan)
age_v_SV_mantel <- mantel(geno3_dist_mat, age_dist_mat, permutations = 500)
# Mantel statistic r: 0.8477 
#      Significance: 0.003992 
# Upper quantiles of permutations (null model):
#   90%   95% 97.5%   99% 
# 0.298 0.425 0.797 0.816 

age_v_SV_man_v2 <- mantel(geno3_dist_mat, age_dist_mat_v2, permutations = 500)
# Mantel statistic r: 0.8275 
#       Significance: 0.001996 
# Upper quantiles of permutations (null model):
#   90%   95% 97.5%   99% 
# 0.307 0.428 0.624 0.777

age_v_SV_man_v3 <- mantel(geno3_dist_mat, age_dist_mat_v3, permutations = 500)
# Mantel statistic r: 0.9386 
#       Significance: 0.001996 
# Upper quantiles of permutations (null model):
#  90%   95% 97.5%   99% 
# 0.202 0.370 0.477 0.744

# note: using only node ages, rather than incuding branch ages, provides 
#  higher r with Mantel test

# See about modeling 13 vs 14 to try to get an estimate for the time
#   between the trees

####
# compare r^2 and p-value for linear models
sv_mat <- as.matrix(geno3_dist_mat)
age_mat <- as.matrix(age_dist_mat)
age_mat_2 <- as.matrix(age_dist_mat_v2)
age_mat_3 <- as.matrix(age_dist_mat_v3)

diag_row_inds <- c(rep(1, times = 7), rep(2, times = 6), rep(3, times = 5),
  rep(4, times = 4), rep(5, times = 3), rep(6, times = 2), rep(7, times = 1))
diag_col_inds <- c(c(2:8), c(3:8), c(4:8), c(5:8), c(6:8), c(7:8), 8)

diag_tot_inds <- cbind(diag_row_inds, diag_col_inds)

sv_vs_age_1 <- lm(as.vector(sv_mat[diag_tot_inds]) ~ 
  as.vector(age_mat[diag_tot_inds]))

c(summary(sv_vs_age_1)$r.squared, summary(sv_vs_age_1)$coefficients[2,4])
# [1] 7.201625e-01 1.162770e-08

sv_vs_age_2 <- lm(as.vector(sv_mat[diag_tot_inds]) ~ 
  as.vector(age_mat_2[diag_tot_inds]))

c(summary(sv_vs_age_2)$r.squared, summary(sv_vs_age_2)$coefficients[2,4])
# [1] 6.842144e-01 5.726345e-08

sv_vs_age_3 <- lm(as.vector(sv_mat[diag_tot_inds]) ~ 
  as.vector(age_mat_3[diag_tot_inds]))

c(summary(sv_vs_age_3)$r.squared, summary(sv_vs_age_3)$coefficients[2,4])
# [1] 8.809570e-01 1.584451e-13

# note: using only node ages provides higher r^2 and higher significance

####
# compare tree 13 v 14

tree_13v14_1 <- lm(as.vector(sv_mat[1:4, 5:8]) ~ as.vector(age_mat[1:4, 5:8]))
c(summary(tree_13v14_1)$r.squared, summary(tree_13v14_1)$coefficients[2,4])
# [1] 0.07154598 0.31656666

tree_13v14_2 <- lm(as.vector(sv_mat[1:4, 5:8]) ~ as.vector(age_mat_2[1:4, 5:8]))
c(summary(tree_13v14_2)$r.squared, summary(tree_13v14_2)$coefficients[2,4])
# NA - there is no variation in matrix

tree_13v14_3 <- lm(as.vector(sv_mat[1:4, 5:8]) ~ as.vector(age_mat_3[1:4, 5:8]))
c(summary(tree_13v14_3)$r.squared, summary(tree_13v14_3)$coefficients[2,4])
# [1] 8.130012e-01 1.831867e-06

# note: using the nodes is a WAY better fit


####
# Within Tree 13

tree_13_row_inds <- c(1,1,1,2,2,3)
tree_13_col_inds <- c(2,3,4,3,4,4)
tree_13_diag_inds <- cbind(tree_13_row_inds, tree_13_col_inds)

tree_13_lm_1 <- lm(sv_mat[tree_13_diag_inds] ~ age_mat[tree_13_diag_inds])
c(summary(tree_13_lm_1)$r.squared, summary(tree_13_lm_1)$coefficients[2,4])
# [1] 0.4477709 0.1460792

tree_13_lm_2 <- lm(sv_mat[tree_13_diag_inds] ~ age_mat_2[tree_13_diag_inds])
c(summary(tree_13_lm_2)$r.squared, summary(tree_13_lm_2)$coefficients[2,4])
# [1] 0.4477709 0.1460792 - same because within-tree distances are the same

tree_13_lm_3 <- lm(sv_mat[tree_13_diag_inds] ~ age_mat_3[tree_13_diag_inds])
c(summary(tree_13_lm_3)$r.squared, summary(tree_13_lm_3)$coefficients[2,4])
# [1] 0.63080501 0.05915436

# note: using the nodes is a slightly better fit
####
# Within Tree 14

tree_14_row_inds <- tree_13_row_inds + 4
tree_14_col_inds <- tree_13_col_inds + 4
tree_14_diag_inds <- cbind(tree_14_row_inds, tree_14_col_inds)

tree_14_lm_1 <- lm(sv_mat[tree_14_diag_inds] ~ age_mat[tree_14_diag_inds])
c(summary(tree_14_lm_1)$r.squared, summary(tree_14_lm_1)$coefficients[2,4])
# [1] 0.67648215 0.04447031

tree_14_lm_2 <- lm(sv_mat[tree_14_diag_inds] ~ age_mat_2[tree_14_diag_inds])
c(summary(tree_14_lm_2)$r.squared, summary(tree_14_lm_2)$coefficients[2,4])
# [1] 0.67648215 0.04447031 - same because within-tree distances are the same

tree_14_lm_3 <- lm(sv_mat[tree_14_diag_inds] ~ age_mat_3[tree_14_diag_inds])
c(summary(tree_14_lm_3)$r.squared, summary(tree_14_lm_3)$coefficients[2,4])
# [1] 0.60963706 0.06681117

# note: including branches provides a slightly better fit

# What if we try to optimize the "underground" distance between trees

# look for best 'r' in Mantel test

intertree_dist_vec <- seq(from = 0, to = 100, by = 5)

stat_list <- list()

for(idv in intertree_dist_vec){
  tmp_dist <- idv
  tmp_age_mat <- age_mat_3
  tmp_age_mat[1:4,5:8] <- tmp_age_mat[1:4,5:8] + idv
  tmp_age_mat[5:8,1:4] <- tmp_age_mat[5:8,1:4] + idv
  tmp_mantel <- mantel(geno3_dist_mat, tmp_age_mat, permutations = 500)
  tmp_stats <- c(tmp_mantel$statistic, tmp_mantel$signif)
  stat_list[[as.character(idv)]] <- tmp_stats
}

stat_mat <- matrix(unlist(stat_list), ncol = 2, byrow = T)
intertree_dist_vec[which.max(stat_mat[,1])]
# 35

age_mat_4 <- age_mat_3
age_mat_4[1:4,5:8] <- age_mat_4[1:4,5:8] + 35

sv_vs_age_4 <- lm(as.vector(sv_mat[diag_tot_inds]) ~
  as.vector(age_mat_4[diag_tot_inds]))

c(summary(sv_vs_age_4)$r.squared, summary(sv_vs_age_4)$coefficients[2,4])
# [1] 9.055464e-01 7.727846e-15

sv_vs_age_3 <- lm(as.vector(sv_mat[diag_tot_inds]) ~
  as.vector(age_mat_3[diag_tot_inds]))
c(summary(sv_vs_age_3)$r.squared, summary(sv_vs_age_3)$coefficients[2,4])
# [1] 8.809570e-01 1.584451e-13

# compare intercept and slopes for linear models comparing different parts
#  of the matrices
summary(sv_vs_age_4)$coefficients[,1]
# 115.77, 2.156

tree_13v14_4 <- lm(as.vector(sv_mat[1:4, 5:8]) ~ as.vector(age_mat_4[1:4, 5:8]))
summary(tree_13v14_4)$coefficients[,1]
# 127.86469, 2.08541

tree_13_lm_4 <- lm(sv_mat[tree_13_diag_inds] ~ age_mat_4[tree_13_diag_inds])
summary(tree_13_lm_4)$coefficients[,1]
# 96.667005, 1.963496

tree_14_lm_4 <- lm(sv_mat[tree_14_diag_inds] ~ age_mat_4[tree_14_diag_inds])
summary(tree_14_lm_4)$coefficients[,1]
# 107.751759, 2.970889

#########3
# What happens if we take out tree 14.3

sv_mat <- as.matrix(geno3_dist_mat)
age_mat <- as.matrix(age_dist_mat)
age_mat_2 <- as.matrix(age_dist_mat_v2)
age_mat_3 <- as.matrix(age_dist_mat_v3)

age_mat_1_adj <- age_mat
age_mat_1_adj[1:4,5:8] <- age_mat[1:4,5:8] + 35
age_mat_1_adj[5:8,1:4] <- age_mat[5:8,1:4] + 35

age_mat_3_adj <- age_mat_3
age_mat_3_adj[1:4,5:8] <- age_mat_3[1:4,5:8] + 35
age_mat_3_adj[5:8,1:4] <- age_mat_3[5:8,1:4] + 35

diag_row_inds <- c(rep(1, times = 7), rep(2, times = 6), rep(3, times = 5),
  rep(4, times = 4), rep(5, times = 3), rep(6, times = 2), rep(7, times = 1))
diag_col_inds <- c(c(2:8), c(3:8), c(4:8), c(5:8), c(6:8), c(7:8), 8)

diag_tot_inds <- cbind(diag_row_inds, diag_col_inds)

b143_d_tot_rm_inds <- c(which(diag_row_inds == 7), which(diag_col_inds == 7))


sv_vs_age_no143_1 <- lm(sv_mat[diag_tot_inds[-b143_d_tot_rm_inds, ]] ~
  (age_mat_1_adj[diag_tot_inds[-b143_d_tot_rm_inds, ]]))

sv_vs_age_adj_1 <- lm(sv_mat[diag_tot_inds] ~
  (age_mat_1_adj[diag_tot_inds]))

c(summary(sv_vs_age_no143_1)$r.squared, 
  summary(sv_vs_age_no143_1)$coefficients[1,c(1,4)], 
  summary(sv_vs_age_no143_1)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 7.122957e-01 9.868629e+01 2.061873e-02 6.500957e-01 1.522272e-06

c(summary(sv_vs_age_adj_1)$r.squared, 
  summary(sv_vs_age_adj_1)$coefficients[1,c(1,4)],
  summary(sv_vs_age_adj_1)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 7.172967e-01 1.015852e+02 8.914228e-03 7.005228e-01 1.329856e-08

sv_vs_age_no143_3 <- lm(sv_mat[diag_tot_inds[-b143_d_tot_rm_inds, ]] ~
  (age_mat_3_adj[diag_tot_inds[-b143_d_tot_rm_inds, ]]))

sv_vs_age_adj_3 <- lm(sv_mat[diag_tot_inds] ~
  (age_mat_3_adj[diag_tot_inds]))

c(summary(sv_vs_age_no143_3)$r.squared, 
  summary(sv_vs_age_no143_3)$coefficients[1,c(1,4)],
  summary(sv_vs_age_no143_3)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 9.149588e-01 1.047347e+02 2.450511e-05 2.114533e+00 1.275629e-11

c(summary(sv_vs_age_adj_3)$r.squared,  
  summary(sv_vs_age_adj_3)$coefficients[1,c(1,4)],
  summary(sv_vs_age_adj_3)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
#  9.055464e-01 1.157683e+02 9.949764e-07 2.156442e+00 7.727846e-15

# Tree 13 v 14
tree_13v14_adj_1 <- lm(as.vector(sv_mat[1:4, c(5:8)]) ~ 
  as.vector(age_mat_1_adj[1:4, 5:8]))

tree_13v14_no143_1 <- lm(as.vector(sv_mat[1:4, c(5,6,8)]) ~
  as.vector(age_mat_1_adj[1:4, c(5,6,8)]))

c(summary(tree_13v14_adj_1)$r.squared,
  summary(tree_13v14_adj_1)$coefficients[1,c(1,4)],
  summary(tree_13v14_adj_1)$coefficients[2,c(1,4)])
#                    Estimate      Pr(>|t|)      Estimate      Pr(>|t|) 
#   0.07154598 -149.63457894    0.80668342    1.16652849    0.31656666 

c(summary(tree_13v14_no143_1)$r.squared,
  summary(tree_13v14_no143_1)$coefficients[1,c(1,4)],
  summary(tree_13v14_no143_1)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 9.140457e-03 2.317931e+02 7.432634e-01 3.957813e-01 7.675642e-01

tree_13v14_adj_3 <- lm(as.vector(sv_mat[1:4, c(5:8)]) ~
  as.vector(age_mat_3_adj[1:4, 5:8]))

tree_13v14_no143_3 <- lm(as.vector(sv_mat[1:4, c(5,6,8)]) ~
  as.vector(age_mat_3_adj[1:4, c(5,6,8)]))

c(summary(tree_13v14_adj_3)$r.squared,
  summary(tree_13v14_adj_3)$coefficients[1,c(1,4)],
  summary(tree_13v14_adj_3)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 8.130012e-01 1.278647e+02 1.428752e-02 2.085410e+00 1.831867e-06

c(summary(tree_13v14_no143_3)$r.squared,
  summary(tree_13v14_no143_3)$coefficients[1,c(1,4)],
  summary(tree_13v14_no143_3)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 8.387610e-01 1.376270e+02 1.022231e-02 1.926100e+00 2.883322e-05

# Within Tree 14
tree_14_row_inds <- tree_13_row_inds + 4
tree_14_col_inds <- tree_13_col_inds + 4
tree_14_diag_inds <- cbind(tree_14_row_inds, tree_14_col_inds)

b14_3_diag_remove <- c(2,4,6)

tree_14_lm_1_no143 <- lm(sv_mat[tree_14_diag_inds[-b14_3_diag_remove,]] ~
  age_mat_1_adj[tree_14_diag_inds[-b14_3_diag_remove,]])

tree_14_lm_1_adj <- lm(sv_mat[tree_14_diag_inds] ~
  age_mat_1_adj[tree_14_diag_inds])

tree_14_lm_3_no143 <- lm(sv_mat[tree_14_diag_inds[-b14_3_diag_remove,]] ~ 
  age_mat_3_adj[tree_14_diag_inds[-b14_3_diag_remove,]])

tree_14_lm_3_adj <- lm(sv_mat[tree_14_diag_inds] ~
  age_mat_3_adj[tree_14_diag_inds])

c(summary(tree_14_lm_1_adj)$r.squared,
  summary(tree_14_lm_1_adj)$coefficients[1,c(1,4)],
  summary(tree_14_lm_1_adj)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
#  0.67648215 -46.04744788   0.67041464   1.91528876   0.04447031

c(summary(tree_14_lm_1_no143)$r.squared,
  summary(tree_14_lm_1_no143)$coefficients[1,c(1,4)],
  summary(tree_14_lm_1_no143)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
#   0.9258185 -166.8333871    0.3788663    2.6662900    0.1756102

c(summary(tree_14_lm_3_adj)$r.squared,
  summary(tree_14_lm_3_adj)$coefficients[1,c(1,4)],
  summary(tree_14_lm_3_adj)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
#  0.60963706 107.75175944   0.13607459   2.97088932   0.06681117

c(summary(tree_14_lm_3_no143)$r.squared,
  summary(tree_14_lm_3_no143)$coefficients[1,c(1,4)],
  summary(tree_14_lm_3_no143)$coefficients[2,c(1,4)])
#                Estimate    Pr(>|t|)    Estimate    Pr(>|t|) 
#  0.3484206 107.8254848   0.6434011   2.3954294   0.5980413 

################
# What's the effect of removing both 14.3 AND 13.2
age_mat_1_adj <- age_mat
age_mat_1_adj[1:4,5:8] <- age_mat[1:4,5:8] + 35
age_mat_1_adj[5:8,1:4] <- age_mat[5:8,1:4] + 35

age_mat_3_adj <- age_mat_3
age_mat_3_adj[1:4,5:8] <- age_mat_3[1:4,5:8] + 35
age_mat_3_adj[5:8,1:4] <- age_mat_3[5:8,1:4] + 35

diag_row_inds <- c(rep(1, times = 7), rep(2, times = 6), rep(3, times = 5),
  rep(4, times = 4), rep(5, times = 3), rep(6, times = 2), rep(7, times = 1))
diag_col_inds <- c(c(2:8), c(3:8), c(4:8), c(5:8), c(6:8), c(7:8), 8)

diag_tot_inds <- cbind(diag_row_inds, diag_col_inds)

rm_d_tot_rm_inds <- unique(c(which(diag_row_inds == 7), 
  which(diag_col_inds == 7), which(diag_row_inds == 2), 
  which(diag_col_inds == 2)))

sv_vs_age_novar_1 <- lm(sv_mat[diag_tot_inds[-rm_d_tot_rm_inds, ]] ~
  (age_mat_1_adj[diag_tot_inds[-rm_d_tot_rm_inds, ]]))

sv_vs_age_adj_1 <- lm(sv_mat[diag_tot_inds] ~
  (age_mat_1_adj[diag_tot_inds]))

c(summary(sv_vs_age_adj_1)$r.squared,
  summary(sv_vs_age_adj_1)$coefficients[1,c(1,4)],
  summary(sv_vs_age_adj_1)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 7.172967e-01 1.015852e+02 8.914228e-03 7.005228e-01 1.329856e-08

c(summary(sv_vs_age_novar_1)$r.squared,
  summary(sv_vs_age_novar_1)$coefficients[1,c(1,4)],
  summary(sv_vs_age_novar_1)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 6.424255e-01 1.048133e+02 6.653913e-02 6.009121e-01 3.270481e-04

sv_vs_age_novar_3 <- lm(sv_mat[diag_tot_inds[-rm_d_tot_rm_inds, ]] ~
  (age_mat_3_adj[diag_tot_inds[-rm_d_tot_rm_inds, ]]))

sv_vs_age_adj_3 <- lm(sv_mat[diag_tot_inds] ~
  (age_mat_3_adj[diag_tot_inds]))

c(summary(sv_vs_age_adj_3)$r.squared,
  summary(sv_vs_age_adj_3)$coefficients[1,c(1,4)],
  summary(sv_vs_age_adj_3)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
#  9.055464e-01 1.157683e+02 9.949764e-07 2.156442e+00 7.727846e-15

c(summary(sv_vs_age_novar_3)$r.squared,
  summary(sv_vs_age_novar_3)$coefficients[1,c(1,4)],
  summary(sv_vs_age_novar_3)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 8.880114e-01 9.945070e+01 2.250268e-03 2.105850e+00 1.508193e-07 

# Tree 13 v 14
tree_13v14_adj_1 <- lm(as.vector(sv_mat[1:4, c(5:8)]) ~
  as.vector(age_mat_1_adj[1:4, 5:8]))

tree_13v14_novar_1 <- lm(as.vector(sv_mat[c(1,3,4), c(5,6,8)]) ~
  as.vector(age_mat_1_adj[c(1,3,4), c(5,6,8)]))

c(summary(tree_13v14_adj_1)$r.squared,
  summary(tree_13v14_adj_1)$coefficients[1,c(1,4)],
  summary(tree_13v14_adj_1)$coefficients[2,c(1,4)])
#                    Estimate      Pr(>|t|)      Estimate      Pr(>|t|) 
#   0.07154598 -149.63457894    0.80668342    1.16652849    0.31656666 

c(summary(tree_13v14_novar_1)$r.squared,
  summary(tree_13v14_novar_1)$coefficients[1,c(1,4)],
  summary(tree_13v14_novar_1)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 0.001095912 489.379465485   0.547654149  -0.128861133   0.932621500

tree_13v14_adj_3 <- lm(as.vector(sv_mat[1:4, c(5:8)]) ~
  as.vector(age_mat_3_adj[1:4, 5:8]))

tree_13v14_novar_3 <- lm(as.vector(sv_mat[c(1,2,4), c(5,6,8)]) ~
  as.vector(age_mat_3_adj[c(1,2,4), c(5,6,8)]))

c(summary(tree_13v14_adj_3)$r.squared,
  summary(tree_13v14_adj_3)$coefficients[1,c(1,4)],
  summary(tree_13v14_adj_3)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 8.130012e-01 1.278647e+02 1.428752e-02 2.085410e+00 1.831867e-06

c(summary(tree_13v14_novar_3)$r.squared,
  summary(tree_13v14_novar_3)$coefficients[1,c(1,4)],
  summary(tree_13v14_novar_3)$coefficients[2,c(1,4)])
#                  Estimate     Pr(>|t|)     Estimate     Pr(>|t|) 
# 8.510699e-01 1.427142e+02 2.437214e-02 1.896710e+00 3.946807e-04

quit(save = 'n')







