# Process .lmiss files generated by VCFtools to get a sense of missing data
#  for each sample in the combo VCF files

# LOAD LIBRARIES #

# LOAD DATA #
newPB_info_dir <- '/home/t4c1/WORK/grabowsk/data/poplar_branches/SV_calling_analysis/new_PB_SVcaller/tmp/'

# SET CONSTANTS #

# SET VARIABLES #

# SET OUTPUT INFO #
newPB_miss_out_file <- 'newPB_missing_genos.txt'

##############
# FUNCTIONS FOR ANALYSIS

process_miss_data <- function(file_name_vec){
  n_miss_vec <- c()
  for(m_f in file_name_vec){
    tmp_miss_data <- read.table(m_f, header = T, stringsAsFactors = F, 
      sep = '\t')
    tmp_miss <- nrow(tmp_miss_data) - table(tmp_miss_data$N_MISS)[1]
    n_miss_vec <- c(n_miss_vec, tmp_miss)
  }
  return(n_miss_vec)
}

# New PacBio Pipeline missingness
newPB_lmiss_files <- system(paste('ls ', newPB_info_dir, '*missing.lmiss', 
  sep = ''), intern = T)

newPB_lib_names <- gsub('_combo_missing.lmiss', '', gsub(paste(newPB_info_dir, 
  'pop_branches_newPB_', sep = ''), '', newPB_lmiss_files))

newPB_miss_vec <- process_miss_data(newPB_lmiss_files)

newPB_miss_df <- data.frame(lib = newPB_lib_names, 
  newPB_n_miss_geno = newPB_miss_vec, stringsAsFactors = F)

newPB_tot_out <- paste(newPB_info_dir, newPB_miss_out_file, sep = '')
write.table(newPB_miss_df, file = newPB_tot_out, quote = F, sep = '\t', 
  row.names = F, col.names = T)

quit(save = 'no')

